### ISSUE TITLE
Cannot add WorkItemLinks to Soap workitems. 

### ISSUE THREAD

**Issue by pelavall** [MicrosoftEdge/Microsoft.Qwiq#202]
This feature was removed with commit 0e979122, by removing Created

**Comment by rjmurillo** [comment]
There should be another way to do this (either a proper method or an extension method), which is only available on the SOAP instance. I vaguely remember having something else that more closely matched the REST naming convention, but was not implemented for both clients since REST is read-only.

**Comment by pelavall** [comment]
From what I look around, they extension methods to use this use the CreateRelatedLink(or similar) method, which was removed, I think by mistake, when we removed some obsolete code, we had two definition of CreateRelatedLink, one got removed as a duplicate/obsolete, but that was the only one which actually had an implementation in the soap workitem.

**Comment by pelavall** [comment]
Resolved by #203
